models:
  - name: dim_occupation
    description: "Storing data about unique occupations or job titles held by individuals."
  - name: dim_employer
    description: "Information regarding about the employers such as name, workplace address, organisation number etc."
  - name: dim_job_details
    description: "Capturing specific details about jobs, such as responsibilities, levels, or categories."
  - name: dim_auxilliary_attributes
    description: "Storing additional or supporting attributes related to occupations or employees."

  - name: fct_job_ads
    description: "The facts are relevance and vacancies."
    columns:
      - name: job_details_id
        description: "Foreign key pointing to the associated job details such as employment type and salary type."
        tests:
          - not_null
          - relationships:
              to: ref('dim_job_details')
              field: job_details_id

      - name: employer_id
        description: "Identifies the employer associated with this record, including company name and related information"
        tests:
          - not_null
          - relationships:
              to: ref('dim_employer')
              field: employer_id

      - name: occupation_id
        description: "Foreign key, a surrogate key generated for each unique occupation."
        tests:
          - not_null
          - relationships:
              to: ref('dim_occupation')
              field: occupation_id

      - name: auxilliary_attributes_id
        description: "Connects to additional attributes related to the record"
        tests:
          - not_null
          - relationships:
              to: ref('dim_auxilliary_attributes')
              field: auxilliary_attributes_id

      - name: some_float_column
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: float

      - name: vacancies
        tests: 
          - dbt_expectations.expect_column_quantile_values_to_be_between:
              quantile: 0.99
              min_value: 1
              max_value: 50
          
          - dbt_expectations.expect_column_max_to_be_between:
              min_value: 1
              max_value: 50
              config:
                severity: warn

          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: number
