models:
  - name: fct_job_ads
    columns:
      - name: job_details_id
        tests:
          - not_null
          - relationships:
              to: ref('dim_job_details')
              field: job_details_id

      - name: employer_id
        tests:
          - not_null
          - relationships:
              to: ref('dim_employer')
              field: employer_id

      - name: occupation_id
        tests:
          - not_null
          - relationships:
              to: ref('dim_occupation')
              field: occupation_id

      - name: auxilliary_attributes_id
        tests:
          - not_null
          - relationships:
              to: ref('dim_auxilliary_attributes')
              field: auxilliary_attributes_id

      - name: some_float_column
        tests:
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: float

      - name: vacancies
        tests: 
          - dbt_expectations.expect_column_quantile_values_to_be_between:
              quantile: 0.99
              min_value: 1
              max_value: 50
          
          - dbt_expectations.expect_column_max_to_be_between:
              min_value: 1
              max_value: 50
              config:
                severity: warn

          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: number
